### ISSUE TITLE
Runtime `java.lang.AbstractMethodError` when combining refinement erasure, value class erasure, and generic type erasure

### ISSUE THREAD

**Issue by dzanot** [fthomas/refined#1174]
This one was a doozy but I was able to minimize a repro: 
https://scastie.scala-lang.org/WECVykZxTBW4dyiJpbvRiQ

for posterity:
```scala
import cats.effect.IO
import eu.timepit.refined.refineV
import eu.timepit.refined.api.Refined
import eu.timepit.refined.numeric.NonNegative
case class Foo(value: Int) extends AnyVal
case class Bar(value: String) extends AnyVal
case class Baz(value: Long Refined NonNegative) extends AnyVal
trait OuterThing[F[_]] {
  def maybeBaz(foo: Foo, bar: Bar, baz: Option[Baz]): F[Unit]
}
final class OuterThingImpl[F[_]](inner: InnerThing[F]) extends OuterThing[F] {
  override def maybeBaz(foo: Foo, bar: Bar, baz: Option[Baz]): F[Unit] = 
    baz.fold(inner.withoutBaz(foo, bar))(inner.withBaz(foo, bar, _)) //at runtime this tries to call InnerThing.withBaz(foo: Foo, bar: Bar, baz: long)
}

trait InnerThing[F[_]]{
  def withBaz(foo: Foo, bar: Bar, baz: Baz): F[Unit]
  def withoutBaz(foo: Foo, bar: Bar): F[Unit]
}

object Main extends cats.effect.IOApp.Simple {
  val testInnerImpl = new InnerThing[IO] {
    override def withBaz(foo: Foo, bar: Bar, baz: Baz): IO[Unit] = IO.println("withBaz")
    override def withoutBaz(foo: Foo, bar: Bar): IO[Unit] = IO.println("withoutBaz")
  }
  val outer = new OuterThingImpl[IO](testInnerImpl)
  val nonNeg: Long Refined NonNegative = refineV[NonNegative](1l).toOption.get

  
  val run = IO.println("Hello") >> outer.maybeBaz(Foo(1), Bar("1"), None) >> outer.maybeBaz(Foo(1), Bar("1"), Some(Baz(nonNeg))) >> IO.println("Goodbye")
}
```

Yields:
```
Hello
withoutBaz
java.lang.AbstractMethodError: Receiver class Main$$anon$1 does not define or inherit an implementation of the resolved method 'abstract java.lang.Object withBaz(int, java.lang.String, long)' of interface InnerThing.
	at OuterThingImpl.maybeBaz$$anonfun$2(main.scala:13)
	at OuterThingImpl.maybeBaz$$anonfun$adapted$1(main.scala:13)
	at scala.Option.fold(Option.scala:263)
	at OuterThingImpl.maybeBaz(main.scala:13)
	at Main$.$init$$$anonfun$2(main.scala:30)
	at cats.effect.IO.$greater$greater$$anonfun$1(IO.scala:143)
	at cats.effect.IOFiber.succeeded(IOFiber.scala:1177)
	at cats.effect.IOFiber.runLoop(IOFiber.scala:966)
	at cats.effect.IOFiber.execR(IOFiber.scala:1324)
	at cats.effect.IOFiber.run(IOFiber.scala:118)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:555)
```

If you drop the `extends AnyVal` it works as expected

**Comment by dzanot** [comment]
Oh yeah, the `F[_]` style algebras are at play here as well. Using concrete IO throughout is working as well: https://scastie.scala-lang.org/Xg7fHQxVSjSkm3sJJIccBQ

**Comment by dzanot** [comment]
Good News: I was able to repro this with opaque types: https://scastie.scala-lang.org/RRVzsTC4Q6WyUpkyikoaKg
Going to re-open this issue in the dotty project

**Comment by dzanot** [comment]
https://github.com/lampepfl/dotty/issues/17281
