### ISSUE TITLE
refineLit does not work with predicates that take an implicit shapeless.Witness.Aux[T]

### ISSUE THREAD

**Issue by fthomas** [fthomas/refined#2]
Using `MatchesRegex` works with `refine` but currently fails with `refineLit`. This test yields the compilation error given below:

```scala
val W = shapeless.Witness
property("refineLit success with MatchesRegex") = secure {
  def ignore: String @@ MatchesRegex[W.`"[0-9]+"`.T] =
    refineLit[MatchesRegex[W.`"[0-9]+"`.T], String]("123")
  true
}
```

```
[error] refined/src/test/scala/eu/timepit/refined/RefinedSpec.scala:66: exception during macro expansion:
[error] scala.tools.reflect.ToolBoxError: reflective compilation has failed:
[error]
[error] overriding value value in trait Witness of type fresh$macro$5.this.T;
[error] value value has incompatible type
[error] at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.throwIfErrors(ToolBoxFactory.scala:316)
[error] at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.wrapInPackageAndCompile(ToolBoxFactory.scala:198)
[error] at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.compile(ToolBoxFactory.scala:252)
[error] at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$$anonfun$compile$2.apply(ToolBoxFactory.scala:429)
[error] at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$$anonfun$compile$2.apply(ToolBoxFactory.scala:422)
[error] at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.liftedTree2$1(ToolBoxFactory.scala:355)
[error] at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.apply(ToolBoxFactory.scala:355)
[error] at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.compile(ToolBoxFactory.scala:422)
[error] at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.eval(ToolBoxFactory.scala:444)
[error] at scala.reflect.macros.contexts.Evals$class.eval(Evals.scala:20)
[error] at scala.reflect.macros.contexts.Context.eval(Context.scala:6)
[error] at eu.timepit.refined.internal.package$.refineLitImpl(package.scala:13)
[error] refineLit[MatchesRegex[W.`"[0-9]+"`.T], String]("123")
```

The exception originates from this line in the `refineLitImpl` macro:
```scala
val predicate: Predicate[P, T] = c.eval(c.Expr(c.untypecheck(p.tree)))
```

**Comment by fthomas** [comment]
This happens with all predicates that take an implicit `shapeless.Witness.Aux[T]`.

Calling `show` on a expression that should be evaluated yields:
```scala
Expr[eu.timepit.refined.Predicate[eu.timepit.refined.generic.Equal[Int(0)],Int]](eu.timepit.refined.generic.equalPredicate[Int, Int(0)]({
  final class fresh$macro$2 extends AnyRef with _root_.shapeless.Witness {
    def <init>() = {
      super.<init>();
      ()
    };
    type T = Int(0);
    private[this] val value: Int(0) = 0;
    <stable> <accessor> def value: Int = 0
  };
  new fresh$macro$2()
}))
```

**Comment by fthomas** [comment]
I asked on SO for help: http://stackoverflow.com/questions/30436005/evaluating-an-expression-of-type-shapeless-witness-auxt-in-a-macro-fails
