### ISSUE TITLE
The autoRefine macro crashes in the 2.10 REPL

### ISSUE THREAD

**Issue by fthomas** [fthomas/refined#295]
Reported by @vlovgr here: https://gitter.im/fthomas/refined?at=593afdcb7503e2b70629858d

For example
```scala
scala> 1: PosInt
<console>:47: error: exception during macro expansion: 
java.lang.ClassCastException: eu.timepit.refined.api.Validate$$anon$2 cannot be cast to eu.timepit.refined.api.Validate
    at eu.timepit.refined.macros.RefineMacro.impl(RefineMacro.scala:23)
    at eu.timepit.refined.macros.RefineMacro$.impl(RefineMacro.scala:9)
```
can be reproduced in the 2.10 REPL:
```sbt
> ++2.10.6
> console
```

**Comment by fthomas** [comment]
I don't know why, but I can no longer reproduce this issue:
```sbt
$ sbt
...
sbt:refined> ++2.10.6
[info] Setting Scala version to 2.10.6 on 17 projects.
...
sbt:refined> clean
sbt:refined> console
...
[info] Compiling 34 Scala sources to refined/modules/core/jvm/target/scala-2.10/classes ...
[info] Done compiling.
[info] Starting scala interpreter...
...
Welcome to Scala version 2.10.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_151).
Type in expressions to have them evaluated.
Type :help for more information.

scala> 1: PosInt
res0: eu.timepit.refined.types.all.PosInt = 1
```

**Comment by vil1** [comment]
I managed to reproduce this issue on a project where the https://github.com/tek/splain plugin was activated.

```scala
scalaVersion in ThisBuild := "2.12.4"

libraryDependencies += "eu.timepit" %% "refined" % "0.8.7"

addCompilerPlugin("io.tryp" %% "splain" % "0.2.7" cross CrossVersion.patch)
```

```
[info] Starting scala interpreter...
Welcome to Scala 2.12.4 (OpenJDK 64-Bit Server VM, Java 1.8.0_151).
Type in expressions for evaluation. Or try :help.

scala> import eu.timepit.refined._, api._, auto._, char._, generic._, collection._
import eu.timepit.refined._
import api._
import auto._
import char._
import generic._
import collection._

scala> val str: String Refined Forall[UpperCase] = "FOO"
<console>:29: error: exception during macro expansion:
java.lang.ClassCastException: eu.timepit.refined.api.Validate$$anon$1 cannot be cast to eu.timepit.refined.api.Validate
	at eu.timepit.refined.macros.RefineMacro.$anonfun$validateInstance$1(RefineMacro.scala:57)
	at scala.Option.getOrElse(Option.scala:121)
	at eu.timepit.refined.macros.RefineMacro.validateInstance(RefineMacro.scala:57)
	at eu.timepit.refined.macros.RefineMacro.impl(RefineMacro.scala:27)

       val str: String Refined Forall[UpperCase] = "FOO"
```

The ClassCastException only shows up in the scala REPL, the same code compiles just fine when put in a scala file. Everything is back to normal when I remove splain.

**Comment by fthomas** [comment]
Thanks for the report @vil1. I've no immediate idea what we could do differently in refined to avoid that exception.
