### ISSUE TITLE
refineLit does not work with Greater on the first try

### ISSUE THREAD

**Issue by fthomas** [fthomas/refined#3]
This is a reproducible REPL session after running `sbt clean` and `sbt console`:
```
Welcome to Scala version 2.11.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_76).
Type in expressions to have them evaluated.
Type :help for more information.

scala> refineLit[Greater[_10], Int](15)
<console>:31: error: exception during macro expansion:
java.lang.IndexOutOfBoundsException: 0
        at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:65)
        at scala.collection.immutable.List.apply(List.scala:84)
        at scala.reflect.internal.Importers$StandardImporter.recreateOrRelink$1(Importers.scala:170)
        at scala.reflect.internal.Importers$StandardImporter.importSymbol(Importers.scala:210)
        at scala.reflect.internal.Importers$StandardImporter.recreateType(Importers.scala:224)
        at scala.reflect.internal.Importers$StandardImporter.importType(Importers.scala:284)
        at scala.reflect.internal.Importers$StandardImporter$$anonfun$recreateType$1.apply(Importers.scala:224)
        at scala.reflect.internal.Importers$StandardImporter$$anonfun$recreateType$1.apply(Importers.scala:224)
        at scala.collection.immutable.List.map(List.scala:273)
        at scala.reflect.internal.Importers$StandardImporter.recreateType(Importers.scala:224)
        at scala.reflect.internal.Importers$StandardImporter.importType(Importers.scala:284)
        at scala.reflect.internal.Importers$StandardImporter.recreateSymbol(Importers.scala:128)
        at scala.reflect.internal.Importers$StandardImporter.scala$reflect$internal$Importers$StandardImporter$$cachedRecreateSymbol$1(Importers.scala:145)
        at scala.reflect.internal.Importers$StandardImporter.recreateOrRelink$1(Importers.scala:193)
        at scala.reflect.internal.Importers$StandardImporter.importSymbol(Importers.scala:210)
        at scala.reflect.internal.Importers$StandardImporter$$anonfun$recreateType$4.apply(Importers.scala:248)
        at scala.reflect.internal.Importers$StandardImporter$$anonfun$recreateType$4.apply(Importers.scala:248)
        at scala.reflect.internal.Scopes$Scope.foreach(Scopes.scala:373)
        at scala.reflect.internal.Importers$StandardImporter.recreateType(Importers.scala:248)
        at scala.reflect.internal.Importers$StandardImporter.importType(Importers.scala:284)
        at scala.reflect.internal.Importers$StandardImporter$$anon$1.complete(Importers.scala:75)
        at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1488)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$1.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:174)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127)
        at scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
        at scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:123)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$1.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:174)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.info(SynchronizedSymbols.scala:127)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$1.info(SynchronizedSymbols.scala:174)
        at scala.reflect.internal.Importers$StandardImporter.recreateOrRelink$1(Importers.scala:167)
        at scala.reflect.internal.Importers$StandardImporter.importSymbol(Importers.scala:210)
        at scala.reflect.internal.Importers$StandardImporter.recreateType(Importers.scala:228)
        at scala.reflect.internal.Importers$StandardImporter.importType(Importers.scala:284)
        at scala.reflect.internal.Importers$StandardImporter.recreateType(Importers.scala:228)
        at scala.reflect.internal.Importers$StandardImporter.importType(Importers.scala:284)
        at scala.reflect.internal.Importers$StandardImporter.recreateType(Importers.scala:224)
        at scala.reflect.internal.Importers$StandardImporter.importType(Importers.scala:284)
        at scala.reflect.internal.Importers$StandardImporter.recreatedTreeCompleter(Importers.scala:302)
        at scala.reflect.internal.Importers$StandardImporter$$anonfun$importTree$1.apply$mcV$sp(Importers.scala:417)
        at scala.reflect.internal.Importers$StandardImporter.tryFixup(Importers.scala:49)
        at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:418)
        at scala.reflect.internal.Importers$StandardImporter$$anonfun$recreateTree$17.apply(Importers.scala:367)
        at scala.reflect.internal.Importers$StandardImporter$$anonfun$recreateTree$17.apply(Importers.scala:367)
        at scala.collection.immutable.List.map(List.scala:273)
        at scala.reflect.internal.Importers$StandardImporter.recreateTree(Importers.scala:367)
        at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:415)
        at scala.reflect.internal.Importers$StandardImporter.recreateTree(Importers.scala:370)
        at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:415)
        at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:29)
        at scala.reflect.macros.contexts.Evals$class.eval(Evals.scala:19)
        at scala.reflect.macros.contexts.Context.eval(Context.scala:6)
        at eu.timepit.refined.internal.package$.refineLitImpl(package.scala:13)

              refineLit[Greater[_10], Int](15)
                                          ^

scala> refineLit[Greater[_10], Int](15)
res1: shapeless.tag.@@[Int,eu.timepit.refined.numeric.Greater[shapeless.nat._10]] = 15
```

The exception does not happen on the second try. Seems to happen only with predicates that take `Nat`s.

**Comment by fthomas** [comment]
The stack trace looks similar to the stack trace in https://issues.scala-lang.org/browse/SI-9218
